name: Maltese Unittests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Tabby OSS Cad Suite (from YosysHQ)
      run: |
        cd /home/runner/work/
        wget -q https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2021-09-23/oss-cad-suite-linux-x64-20210923.tgz
        tar -xf oss-cad-suite-linux-x64-20210923.tgz
        rm /home/runner/work/oss-cad-suite/bin/yices*
        ls /home/runner/work/oss-cad-suite/bin
        echo "/home/runner/work/oss-cad-suite/bin" >> $GITHUB_PATH

    - name: Install CVC4
      run: sudo apt-get install -y cvc4

    - name: Install Yices
      run: |
        cd /home/runner/work
        wget -q https://yices.csl.sri.com/releases/2.6.2/yices-2.6.2-x86_64-pc-linux-gnu-static-gmp.tar.gz
        tar -xf yices-2.6.2-x86_64-pc-linux-gnu-static-gmp.tar.gz
        cd yices-2.6.2
        sudo ./install-yices /usr

    - name: Print Solver Versions and Paths
      run: |
        echo "Yices"
        yices-smt2 --version
        which yices-smt2
        echo ""
        echo "CVC4"
        cvc4 --version
        which cvc4
        echo ""
        echo "Btormc"
        btormc --version --copyright
        which btormc
        echo ""
        echo "Z3"
        z3 --version
        which z3

    - name: Install Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: openjdk@1.11

    - name: Compile Maltese
      run: sbt compile

    - name: Run Unittests
      timeout-minutes: 3
      run: sbt test
